- hosts: localhost
  vars_files:
    - host_vars/multi_nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: create_multiple_instances
    - role: openstack-volume-snapshot

- hosts: appservers
  remote_user: ubuntu
  vars_files:
    - host_vars/m_vol.yaml
  gather_facts: false
  pre_tasks:
    - name: 'Install Python2'
      raw: sudo apt-get update; sudo apt-get -y install python
  roles:
    - role: write_proxy 
    - role: mount_volume  
         
                                                                 
- hosts: webservers
  remote_user: ubuntu
  become: yes
  vars_files:
    - host_vars/m_vol.yaml
  gather_facts: false
  pre_tasks:
     - name: 'Install Python2'
       raw: sudo apt-get update; sudo apt-get -y install python
  roles:
    - role: write_proxy
    - role: mount_volume
