- hosts: localhost
  vars_files:
    - host_vars/multi_nectar.yaml
  gather_facts: true

  roles:
          #  - role: openstack-common
          #  - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: create_multiple_instances
    - role: attach-volume  
      # - role: openstack-volume-snapshot

- hosts: appservers
  become: yes
  remote_user: ubuntu
  vars_files:
    - host_vars/m_vol.yaml
    - host_vars/couch_var.yaml  
  gather_facts: false
  pre_tasks:
    - name: 'Install Python2'
      raw: sudo apt-get update; sudo apt-get -y install python3
    - lineinfile:
         path: /etc/environment
         line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ groups["appservers"][0] }}'    
  roles:
    - role: write_proxy 
    - role: mount_volume  
    - role: apt-packages
    - role: install-couchdb
    - role: edit-hosts
    - role: bind-addr
    - role: admin-user
    - role: restart-couchdb
      # - role: install-pip3
      # - role: install-harv-dependencies
      # - role: copy-harv-folder
      # - role: execute-harvesters


- hosts: webservers
  remote_user: ubuntu
  become: yes
  vars_files:
    - host_vars/m_vol.yaml
    - host_vars/couch_var.yaml
  gather_facts: false
  pre_tasks:
     - name: 'Install Python2'
       raw: sudo apt-get update; sudo apt-get -y install python
     - lineinfile:
          path: /etc/environment
          line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ groups["webservers"][0] }}'
  roles:
    - role: write_proxy
    - role: mount_volume
    - role: apt-packages
    - role: install-couchdb
    - role: edit-hosts
    - role: bind-addr
    - role: admin-user
    - role: restart-couchdb

- hosts: dbservers
  remote_user: ubuntu
  become: yes
  vars_files:
        - host_vars/m_vol.yaml
        - host_vars/couch_var.yaml
  gather_facts: false
  pre_tasks:
      - name: 'Install Python3'
        raw: sudo apt-get update; sudo apt-get -y install python3
      - lineinfile:
           path: /etc/environment
           line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ groups["dbservers"][0] }}'
  roles:
     - role: write_proxy
     - role: mount_volume
     - role: apt-packages
     - role: install-couchdb
     - role: edit-hosts
     - role: bind-addr
     - role: admin-user
     - role: restart-couchdb
     - role: install-pip3
     - role: install-web-dependencies

- hosts: servers
  remote_user: ubuntu
  become: yes
  vars_files:
     - host_vars/m_vol.yaml
     - host_vars/couch_var.yaml
  gather_facts: false
  pre_tasks:
     - name: 'Install Python3'
       raw: sudo apt-get update; sudo apt-get -y install python
     - lineinfile:
        path: /etc/environment
        line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ groups["servers"][0] }}'
  roles:
     - role: write_proxy
     - role: mount_vol_prod1
     - role: apt-packages
     - role: install-couchdb
     - role: edit-hosts
     - role: bind-addr
     - role: admin-user
     - role: restart-couchdb
