---
# Create a security Group
                   
- name: Create a list of security group names
  set_fact: 
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'
                             
- debug:
    msg: "Security group(s) {{ sg_names }} have been created."
                                     
